### ISSUE TITLE
Serious: the plugin locks QGIS

### ISSUE THREAD

**Issue by pcav** [rduivenvoorde/featuregridcreator#3]
After starting the analysis, the plugin apparently locks QGIS, and has no other choice than shutting it down. Nothing shown on the shell.

**Comment by rduivenvoorde** [comment]
never seen this one. Please add more info to reproduce, eg a shapefile of current data you are using?

**Comment by pcav** [comment]
Apparently no attachments here; sending by private email

**Comment by rduivenvoorde** [comment]
shoot, that is true :-) no attachments here...

**Comment by rduivenvoorde** [comment]
![maybeoverflow](https://cloud.githubusercontent.com/assets/731673/6172143/35a3bbd4-b2df-11e4-9618-ce6250240fae.png)

mmm testing here with a province polygon... grid 100x100 meter

it takes a long time, but finishes with 900.000(!) points in the shape you seen on attachement.

Not sure what happens here, apparently it starts of ok, but at a certain moment (integer overflow??) is not working with the 'within' anymore.

As said, the use-case is working plots... so maybe I'll count the number of features on before hand, and just quit if it is more then... 1000 ?

**Comment by rduivenvoorde** [comment]
![selection_150](https://cloud.githubusercontent.com/assets/731673/6172244/cef8ba1e-b2df-11e4-87cf-d39cd59bb4fb.png)

your data by the way seems to work. BUT as said I think the number of features to generate kills the plugin...

**Comment by pcav** [comment]
In fact it eventually get to a result, it just does not give feedback for a long time.
