### ISSUE TITLE
Max X and Y too small

### ISSUE THREAD

**Issue by pcav** [rduivenvoorde/featuregridcreator#4]
Currently only 3 digits are allowed. In several cases one may need much more.

**Comment by rduivenvoorde** [comment]
given that we generate a memory layer, and customers use case was boreholes max 200 meters apart.
Do you the plugin is usefull for use cases where this number is much bigger?
No problem with making it 1000 meter or so, but I have to be carefull with the number of features to generate....

**Comment by pcav** [comment]
On the contrary: a larger value will generate fewer points, so the plugin will be usable over larger areas.
Anyway, the number of features returned is a general phenomenon (e.g. for fTools), and a general solution would be very useful.
