### ISSUE TITLE
Support for additional geometry type QGis.WKBPolygon25D

### ISSUE THREAD

**Issue by eenblam** [rduivenvoorde/featuregridcreator#5]
It was trivial to add this in, but is there a reason that it was excluded from the accepted geometry types? I'm new to GIS in general, so I wouldn't be surprised if there was some issue with 2.5D, but I can't immediately think of why it would matter in this instance.

**Comment by rduivenvoorde** [comment]
@eenblam sorry for the late reply, did not look at the issues recently...

anyway. No no reason at all, if you show me your fix, I'm happy to add it

**Comment by rduivenvoorde** [comment]
@eenblam I'm fixing stuff on the plugin, can you please sent me your fix to make it work with 2.5D ?

**Comment by rduivenvoorde** [comment]
@eenblam ping can you let me know what you want changed?

**Comment by eenblam** [comment]
@rduivenvoorde My fix was a one-off script. I haven't revisited the problem since, and I can't recall the specific error I was getting. I need to reinstall QGis and check that everything still works as expected. Sorry for being MIA and not giving more info when I opened the issue.

If you want to close the issue but leave comments open, I can come back with a link to a gist or make a pull-request when I've had a minute to test it properly.

**Comment by rduivenvoorde** [comment]
Implemented in version 1.2.1 
Closing this one
