### ISSUE TITLE
Changing XY Distance Direction to work with cm

### ISSUE THREAD

**Issue by aau04149** [rduivenvoorde/featuregridcreator#7]
Hey

I'm new to this so may be going about this the wrong way.  I'm using this tool to create parking spaces of length 5.5m by 2.5m width taken from a line layer.  Is there a way that the Distance X direction can handle cm instead of metres.  My main issue is that creating 5.5m x 2.5m boxes means that I have to choose 5m X direction which overlaps the boxes or 6m which leaves a gap between boxes.

Any help would be appreciated.

Thanks

**Comment by rduivenvoorde** [comment]
@aau04149 only reason we did this is because of the use-case we had. That is: the distance would always be in full meters. It's pretty trivial to make it possible to use decimal numbers too...

plz let me know if still of use

**Comment by aau04149** [comment]
Hi Richard

Thanks for getting back to me. Yeah in my case it would be useful to have the X-Direction work with cm. I've been using the software to create parking spaces of 5.5m that follow around pavements (lines), however the X-Direction only being in metres means that there is a 0.5 overlap. If the X-Distance could be 5.5 then the boxes would be right next to each other without an overlap. 

If you could help me with this then that would be great. 

Many Thanks

Graham S

(Sent from my iPhone)

**Comment by aau04149** [comment]
Hi Richard

Would you be able to help with the above?

Many Thanks

**Comment by rduivenvoorde** [comment]
@aau04149 plz test/see new version 1.2.0

Let me know if not ok.
