### ISSUE TITLE
AttributeError: type object 'UnitType' has no attribute 'Meters'

### ISSUE THREAD

**Issue by pvandegeer** [rduivenvoorde/featuregridcreator#8]
The latest version returns an error as QGis.UnitType.Meters is not recognized.

```
2019-02-16T15:52:25	1	Traceback (most recent call last):
			  File "C:/Users/XXX/.qgis2/python/plugins\FeatureGridCreator\grid_creator.py", line 450, in show_create_features_dialog
			    if self.init_create_features_dialog():
			  File "C:/Users/XXX/.qgis2/python/plugins\FeatureGridCreator\grid_creator.py", line 489, in init_create_features_dialog
			    if layer.crs().mapUnits() != QGis.UnitType.Meters:
			AttributeError: type object 'UnitType' has no attribute 'Meters'
```

The Python enum is QGis.Meters, see: http://geoapis.sourcepole.com/qgispyapi/qgis#QGis.UnitType

**Comment by rduivenvoorde** [comment]
Mmm, which version of QGIS are you running? Because in my QGIS 2.18 both work:

![gnome-shell-screenshot-fdb0wz](https://user-images.githubusercontent.com/731673/52902474-61505c00-3211-11e9-803f-e75b5ca42c2f.png)

**Comment by pvandegeer** [comment]
QGis 2.18.28 32-bit on Windows 10

![image](https://user-images.githubusercontent.com/893868/52905029-4e02b800-3234-11e9-888e-cf2b3f99af52.png)

**Comment by m-kuhn** [comment]
Can you compare sip versions too?

**Comment by rduivenvoorde** [comment]
On Debian I have 4.19.13 (I think?)

Maybe we should show this in About box ?

**Comment by m-kuhn** [comment]
```
import sip
sip.SIP_VERSION_STR
```

**Comment by rduivenvoorde** [comment]
On Linux:
'4.19.13'

On Windows (2.18.27 Osgeo4W install):
'4'14'7

**Comment by m-kuhn** [comment]
Quite some things have changed regarding enums (https://www.riverbankcomputing.com/static/Docs/sip/incompatibilities.html)

I would just stick to the "compatible" version for now

**Comment by pvandegeer** [comment]
> QGis 2.18.28 32-bit on Windows 10
SIP is 4.16.5

**Comment by rduivenvoorde** [comment]
See version 1.2.2, should be fixed now

**Comment by pvandegeer** [comment]
Works for me. 👍
